<?php

namespace ContainerQUL8iUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheeseListingIsPublishedExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\ApiPlatform\CheeseListingIsPublishedExtension' shared autowired service.
     *
     * @return \App\ApiPlatform\CheeseListingIsPublishedExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Extension/QueryCollectionExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Extension/QueryItemExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/src/ApiPlatform/CheeseListingIsPublishedExtension.php';

        return $container->privates['App\\ApiPlatform\\CheeseListingIsPublishedExtension'] = new \App\ApiPlatform\CheeseListingIsPublishedExtension(($container->privates['security.helper'] ?? $container->getSecurity_HelperService()));
    }
}
